### PR TITLE
Fixed xgboost

### PR DESCRIPTION
**Pull request by kamil-kaczmarek**
Fixing #10 

Also added tests and CI - @PiotrJander please check if it is correct.

### CODE REVIEW

**Comment by kamil-kaczmarek** [comment]
@PiotrJander for this - in order to run - I need to somehow install graphviz executables: https://graphviz.org/download/

Normally I would just go with: `$ sudo apt install graphviz` - how to do it in CI?

**Comment by jakubczakon** [comment]
How about

```bash
! sudo apt get install graphviz
```

In one of the cells @kamil-kaczmarek ?

**Comment by kamil-kaczmarek** [comment]
> How about
> 
> ```shell
> ! sudo apt get install graphviz
> ```
> 
> In one of the cells @kamil-kaczmarek ?
> 
> Remember it should work for the user, in the user's notebook.

In this way User cannot provide sudo pass.

**Comment by kamil-kaczmarek** [comment]
> > How about
> > ```shell
> > ! sudo apt get install graphviz
> > ```
> > 
> > 
> > In one of the cells @kamil-kaczmarek ?
> > Remember it should work for the user, in the user's notebook.
> 
> In this way User cannot provide sudo pass.

Here is a solution:


```
!apt install -y graphviz
!pip install graphviz
```

**Comment by kamil-kaczmarek** [comment]
@jakubczakon I can see that only mac-os tests for xgboost are failing.

This is because some libs are missing and they should be installed on CI machine: https://github.com/neptune-ai/neptune-examples/pull/13/checks?check_run_id=1293643635#step:5:194
(not Python libs)

@PiotrJander can you help here?

**Review by jakubczakon — APPROVED** [review]

**Comment by jakubczakon** [comment]
@kamil-kaczmarek it looks good to me. 
Once the installation problems on mac are solved we can merge.

**Comment by PiotrJander** [comment]
I suggest we merge https://github.com/neptune-ai/neptune-examples/pull/14 first - it adds a unified mechanism for testing all examples in the repo in a single workflow, and it installs OpenMP on MacOS servers to enable the XGBoost integration. 

Since that PR adds a unified pipeline workflow for all examples, you could then delete your custom workflow for XGBoost.

But please also have a look at why XGBoost integration fails on Windows CI server.

I think we should always aim for green pipelines, and if we want to exclude a particular integration / test on a particular platform, we should do it in the `test_examples.py` file, which currently use a very simple discovery mechanism and looks like this:

```python
test_files = glob('**/tests/*.py', recursive=True)

@pytest.mark.parametrize("filename", test_files)
def test_examples(filename):
    check_call('ipython ' + filename, shell=True)
```

If, hypothetically, we want to disable testing XGBoost integration on Windows, I would imagine changing this file like this:

```python
test_files = glob('**/tests/*.py', recursive=True)

excluded_files = []

if os.name == 'nt': # if OS is Windows
     excluded_files.extend(glob('integrations/xgboost/tests/*.py', recursive=True))

@pytest.mark.parametrize("filename", [f for f in test_files if f not in excluded_files])
def test_examples(filename):
    check_call('ipython ' + filename, shell=True)
```

or something like this.

**Comment by kamil-kaczmarek** [comment]
@jakubczakon xgboost tests passed. There are problems with `R` and `Neptune-API-Tour`, which should not be fixed in this branch.

**Comment by jakubczakon** [comment]
@kamil-kaczmarek it seems that there are 38 files changed in this PR when in reality it should be way less (there are PL and others in there too). 
Could you please clean it up a bit?

**Comment by jakubczakon** [comment]
@kamil-kaczmarek @PiotrJander I don't think we can exclude windows from tests for xgboost and feel good about it. 
A lot of our users work on Windows, especially people not doing deep learning so we have to figure out what is going on here.

**Comment by kamil-kaczmarek** [comment]
> @kamil-kaczmarek it seems that there are 38 files changed in this PR when in reality it should be way less (there are PL and others in there too).
> Could you please clean it up a bit?

I did rebase, these changes are neutral when compared to master. I also merged unified testing in this branch, to work on the new workflow that @PiotrJander prepared.

**Pull request merged**
